name: Check Commit Hash

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      working-directory: ./version_checker
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Task
      env:
        GITHUB_TOEKN: ${{ secrets.GITHUB_OAUTH_TOKEN }}
      working-directory: ./version_checker
      run: |
        mix version_check.run
